### **univariate feature selection using chi square test**

In [30]:
#out of 8 features of dataset which one is most imp in predicting the class?
# feature extraction with Unbivariate statistical Tests(chi-squared for classification)
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest # for univariate selction
from sklearn.feature_selection import chi2

In [31]:
# load data, patients details taken, identify which variableis most imp in identifying whether patient has diabetes or not
filename='/content/pima-indians-diabetes.data.csv'
# in actual dataset no col names so give col names,Class-y variable
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [32]:
array=dataframe.values
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [33]:
dataframe.shape

(768, 9)

In [34]:
x=array[:,0:8]
y=array[:,8]

# feature extraction
test=SelectKBest(score_func=chi2,k=5) # get top 5 features, K should be less than or equal to total no of features
fit=test.fit(x,y)
# summarize scores
set_printoptions(precision=4)
print(fit.scores_) # will get chi squares for each feature
# for regression: f_regression, mutual_info_regression
# for classification: chi2. f_classif,mutual_info_classif
# for feature 'test':chi square value is 2175.5653 so this is most imp feature,then plas,pedi...,

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [35]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [36]:
# score chi square values in a dataframe
x=pd.DataFrame(fit.scores_).T # .T will transpose list into dataframe


In [37]:
x

0            1          2         3            4           5  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

          6           7  
0  5.392682  181.303689

In [38]:
x.columns=names[:8]
x

preg         plas       pres      skin         test        mass  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

       pedi         age  
0  5.392682  181.303689

In [39]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [40]:
# sort chi square values in ascending or descending values
sorted_x=x.sort_values(by=0,ascending=False,axis=1)
sorted_x

# axis=0:sort along the rows . i.e, you sort the dataframe based on the values in a specific column
# axis=1:sort along the columns . i.e, you sort the dataframe based on the values in a specific row


test         plas         age        mass        preg      skin  \
0  2175.565273  1411.887041  181.303689  127.669343  111.519691  53.10804   

        pres      pedi  
0  17.605373  5.392682

In [41]:
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

### **Recursive Feature Elimination**

In [42]:
# feature extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
# load Data
filename='/content/pima-indians-diabetes.data.csv'

# in actual dataset no col names so give col names,Class-y variable
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)
dataframe


preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [43]:
array=dataframe.values
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [44]:
x=array[:,0:8]
y=array[:,8]
# feature extraction
model=LogisticRegression(max_iter=400) # to find out coefficients of logistic regression for that it need to iterate
# inside logistic regression optimization algorithm is there. using that, coefficients will be estimated
# for that it has to iterate multiple times.default value is 100
rfe=RFE(model) # see best features
fit=rfe.fit(x,y)

In [45]:
# num Features:4 top features are available
fit.n_features_

4

In [46]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [47]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [48]:
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

### Feature Importence using Decision Tree

In [49]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier
# load Data
filename='/content/pima-indians-diabetes.data.csv'

# in actual dataset no col names so give col names,Class-y variable
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=names)
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [50]:
array=dataframe.values
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [51]:
x=array[:,0:8]
y=array[:,8]
# feature extraction
model=DecisionTreeClassifier()
model.fit(x,y)

DecisionTreeClassifier()

In [53]:
model.feature_importances_

array([0.0587, 0.3316, 0.1033, 0.017 , 0.0329, 0.2098, 0.1293, 0.1174])

In [55]:
sorted_list=model.feature_importances_
print('feature importence',sorted_list)# before sorting
sorted_list.sort()
print('sorted feature importence',sorted_list) # after sorting

feature importence [0.0587 0.3316 0.1033 0.017  0.0329 0.2098 0.1293 0.1174]
sorted feature importence [0.017  0.0329 0.0587 0.1033 0.1174 0.1293 0.2098 0.3316]


In [56]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']